### ISSUE TITLE
Question about doctest-discover blog-post

### ISSUE THREAD

**Issue by MaxDaten** [rcook/github-api-haskell#1]
Hi,

I followed your [blog-post](http://blog.rcook.org/blog/2016/doctest-discover-stack/) but without success in a relative simple project, so I peeked into this project to figure some differences out. But you removed the dependency to doctest-discover in 7ccdf598534a0ef232b75faa78cd6315bd54a0ea. Can you elaborate why, maybe in a follow up or update?:) Just out of curiosity. I think I will try your current approach, too.

Greetings & Thanks

**Comment by rcook** [comment]
@MaxDaten: Thanks for pointing out this discrepancy. I found and used [`doctest-discover`](https://github.com/karun012/doctest-discover) (which I still think is an excellent package) while writing the blog post and then decided to take a slightly different approach a few days later. The main motivation behind this was to get the project building with Travis-CI. Since `doctest-discover` is not yet in [Stackage](https://www.stackage.org/), I ran into problems with this (see [failed build](https://travis-ci.org/rcook/github-api-haskell/jobs/108460606), for example). Without this non-Stackage dependency, the project builds reliably in Travis-CI (see [successful build](https://travis-ci.org/rcook/github-api-haskell/builds/106132585)).

I have suggested to the owner of `doctest-discover` that he add it to the Stackage repository, but I don't think he is strongly motivated to do so (see [thread](https://github.com/karun012/doctest-discover/issues/4)). I also tried to get the Travis-CI build working using [`extra-deps`](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#extra-deps) in my `stack.yaml` configuration, but I ran out of patience. I'm sure this is possible and might try it again some time in the future.

For the time being, I've tagged the revision immediately before 7ccdf59 and updated the blog post to reference this tag instead of HEAD. Some time soon I'll write a follow-up post mentioning this.

If you're still having issues, please let me know what build or test failures you're seeing and maybe I can help point you in the right direction.

**Comment by MaxDaten** [comment]
@rcook thanks for your extensive explanation.

I just discovered (https://github.com/yesodweb/wai/commit/52f892c3c9643a7e0f868832c2d783f3678c980d with according commit in doctest: https://github.com/sol/doctest/commit/2f10ffe42683b4e4cdbd57bd54c8b13343474d9a) that since doctest-0.10.1 folders are auto expanded, maybe this is helpful in a further simplification of your doctest main, like this:

```haskell
module Main (main) where

import Test.DocTest (doctest)

main :: IO ()
main = doctest ["src"]
```

This should work, but I have currently some hurdles with (servant) type operators when defining a type over multiple lines. This:

```haskell
type DocumentsAPI =
  Capture "documentId" DocumentId :> 
  Get '[JSON] Document
```

results in an parse error during the doctest phase:

```
parse error on input ‘:>’
```

But maybe the servant people have a clue how to overcome this problem.
